# src/your_project/config/tasks.yaml
recomposition_task:
  description: >
    Extract text and context from the tweet structure.
  expected_output: >
    A dictionary containing the text and context.
  agent: recomposition_agent

translation_task:
  description: >
    Take in the extracted text and context produced by recomposition_task
    Translate the extracted text between English and Chinese considering the provided context.
  expected_output: >
    The translated text.
  agent: translation_agent
