---
config:
  theme: neo-dark
  layout: elk
---
flowchart TD
 subgraph PreparationCrew["PreparationCrew"]
        Twitter("TwitterAPI")
        F["TwitterFetchAgent"]
        M["TranslationManagementAgent"]
        L["LanguageDetectionAgent"]
        C["ContextAgent"]
  end
 subgraph TranslationCrew["TranslationCrew"]
        T1["TranslationAgent 1"]
        T2["TranslationAgent 2"]
        T3["TranslationAgent 3"]
        E["EvaluationAgent"]
        U(("User"))
  end
    Twitter --> F
    F --> M
    M -- text --> L
    M -- list of links --> C
    M -- text + context --> T1 & T2 & T3
    T1 -- translated post --> E
    T2 -- translated post --> E
    T3 -- translated post --> E
    E -- Feedback --> M
    E -- translated text --> U
